#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="${SVNHUB_DATA_DIR:-/var/lib/svnhub/data}"
REPOS_DIR="${SVNHUB_REPOS_DIR:-/var/lib/svnhub/repos}"

mkdir -p "$DATA_DIR" "$REPOS_DIR"

# Ensure auth files exist so Apache can start even before initial setup.
touch "$DATA_DIR/htpasswd"
if [[ ! -f "$DATA_DIR/authz" ]]; then
  cat > "$DATA_DIR/authz" <<'EOF'
# Generated by SvnHub. DO NOT EDIT.

[groups]
admins =
EOF
fi

# Ensure dotnet + apache can both read/write repos and auth files.
# For Docker named volumes this is cheap; for bind mounts with huge data,
# consider chowning on the host instead.
if [[ "${SVNHUB_SKIP_CHOWN:-0}" != "1" ]]; then
  chown -R www-data:www-data "$DATA_DIR" "$REPOS_DIR" || true
fi

dotnet /app/SvnHub.Web.dll &
dotnet_pid=$!

apache2ctl -D FOREGROUND &
apache_pid=$!

term() {
  kill -TERM "$dotnet_pid" "$apache_pid" 2>/dev/null || true
}

trap term SIGTERM SIGINT

wait -n "$dotnet_pid" "$apache_pid" || true
term
wait || true
