#!/usr/bin/env bash
set -euo pipefail

APP_USER="svnhub"
APP_GROUP="svnhub"
DATA_DIR="${SVNHUB_DATA_DIR:-/var/lib/svnhub/data}"
REPOS_DIR="${SVNHUB_REPOS_DIR:-/var/lib/svnhub/repos}"
SVNHUB_UID="${SVNHUB_UID:-10001}"
SVNHUB_GID="${SVNHUB_GID:-10001}"
SVNHUB_FIX_OWNERSHIP="${SVNHUB_FIX_OWNERSHIP:-0}"

is_number() {
  [[ "$1" =~ ^[0-9]+$ ]]
}

is_truthy() {
  [[ "$1" == "1" || "$1" == "true" || "$1" == "yes" || "$1" == "y" ]]
}

is_empty_dir() {
  [[ -z "$(find "$1" -mindepth 1 -maxdepth 1 -print -quit)" ]]
}

configure_identity() {
  if ! is_number "$SVNHUB_UID" || ! is_number "$SVNHUB_GID"; then
    echo "SVNHUB_UID and SVNHUB_GID must be numeric. Got UID='$SVNHUB_UID' GID='$SVNHUB_GID'." >&2
    exit 64
  fi

  groupmod -o -g "$SVNHUB_GID" "$APP_GROUP"
  usermod -o -u "$SVNHUB_UID" -g "$APP_GROUP" "$APP_USER"
}

maybe_init_empty_mount() {
  local path="$1"
  local label="$2"

  if is_empty_dir "$path"; then
    echo "Initializing empty $label directory '$path' for uid=$SVNHUB_UID gid=$SVNHUB_GID."
    chown "$SVNHUB_UID:$SVNHUB_GID" "$path"
    chmod 2770 "$path"
  fi
}

require_dir_access() {
  local path="$1"
  local label="$2"

  if gosu "$APP_USER" test -r "$path" -a -w "$path" -a -x "$path"; then
    return
  fi

  cat >&2 <<EOF
SvnHub cannot read/write $label directory '$path' as $APP_USER (uid=$SVNHUB_UID gid=$SVNHUB_GID).

Fix one of these:
  - set SVNHUB_UID/SVNHUB_GID to match the host owner of the mounted directory;
  - adjust ownership or ACLs on the host;
  - for a new or disposable install, set SVNHUB_FIX_OWNERSHIP=1 to chown recursively at startup.
EOF
  exit 73
}

require_file_access() {
  local path="$1"
  local label="$2"

  if gosu "$APP_USER" test -r "$path" -a -w "$path"; then
    return
  fi

  cat >&2 <<EOF
SvnHub cannot read/write $label file '$path' as $APP_USER (uid=$SVNHUB_UID gid=$SVNHUB_GID).
Fix file ownership or set SVNHUB_FIX_OWNERSHIP=1 for an intentional recursive repair.
EOF
  exit 73
}

mkdir -p "$DATA_DIR" "$REPOS_DIR"
configure_identity

if is_truthy "$SVNHUB_FIX_OWNERSHIP"; then
  echo "Recursively changing ownership of SvnHub data and repositories to uid=$SVNHUB_UID gid=$SVNHUB_GID."
  echo "This is intentional because SVNHUB_FIX_OWNERSHIP=$SVNHUB_FIX_OWNERSHIP."
  chown -R "$SVNHUB_UID:$SVNHUB_GID" "$DATA_DIR" "$REPOS_DIR"
  chmod 2770 "$DATA_DIR" "$REPOS_DIR"
else
  maybe_init_empty_mount "$DATA_DIR" "data"
  maybe_init_empty_mount "$REPOS_DIR" "repositories"
fi

require_dir_access "$DATA_DIR" "data"
require_dir_access "$REPOS_DIR" "repositories"

# Ensure auth files exist so Apache can start even before initial setup.
if [[ ! -f "$DATA_DIR/htpasswd" ]]; then
  install -o "$SVNHUB_UID" -g "$SVNHUB_GID" -m 0660 /dev/null "$DATA_DIR/htpasswd"
fi

if [[ ! -f "$DATA_DIR/authz" ]]; then
  cat > "$DATA_DIR/authz" <<'EOF'
# Generated by SvnHub. DO NOT EDIT.

[groups]
owners =
EOF
  chown "$SVNHUB_UID:$SVNHUB_GID" "$DATA_DIR/authz"
  chmod 0660 "$DATA_DIR/authz"
fi

require_file_access "$DATA_DIR/htpasswd" "htpasswd"
require_file_access "$DATA_DIR/authz" "authz"

export APACHE_RUN_USER="$APP_USER"
export APACHE_RUN_GROUP="$APP_GROUP"
umask 0007

gosu "$APP_USER" dotnet /app/SvnHub.Web.dll &
dotnet_pid=$!

apache2ctl -D FOREGROUND &
apache_pid=$!

term() {
  kill -TERM "$dotnet_pid" "$apache_pid" 2>/dev/null || true
}

trap term SIGTERM SIGINT

wait -n "$dotnet_pid" "$apache_pid" || true
term
wait || true
