using System.ComponentModel;
using System.Security.Cryptography;
using System.Text;
using SvnHub.App.Configuration;
using SvnHub.App.Services;
using SvnHub.App.System;
using SvnHub.Domain;
using SvnHub.Infrastructure.Storage;

namespace SvnHub.Infrastructure.System;

public sealed class AuthFilesWriter : IAuthFilesWriter
{
    private readonly ICommandRunner _runner;
    private readonly SvnHubOptions _options;

    public AuthFilesWriter(ICommandRunner runner, SvnHubOptions options)
    {
        _runner = runner;
        _options = options;
    }

    private string DataDirectory
    {
        get
        {
            return Path.GetFullPath(_options.DataDirectory);
        }
    }

    private string HtpasswdPath => Path.Combine(DataDirectory, "htpasswd");
    private string AuthzPath => Path.Combine(DataDirectory, "authz");

    public Task WriteHtpasswdAsync(IReadOnlyList<PortalUser> users, CancellationToken cancellationToken = default)
    {
        var sb = new StringBuilder();

        foreach (var user in users.Where(u => u.IsActive).OrderBy(u => u.UserName, StringComparer.Ordinal))
        {
            if (string.IsNullOrWhiteSpace(user.SvnBcryptHash))
            {
                continue;
            }

            sb.Append(user.UserName);
            sb.Append(':');
            sb.Append(user.SvnBcryptHash);
            sb.Append('\n');
        }

        AtomicFileWriter.WriteAllText(HtpasswdPath, sb.ToString());
        return Task.CompletedTask;
    }

    public Task WriteAuthzAsync(PortalState state, CancellationToken cancellationToken = default)
    {
        var compiled = CompileAuthz(state);
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by SvnHub. DO NOT EDIT.");
        sb.AppendLine("# SvnHub permission rules are evaluated top-to-bottom; the last matching rule wins.");
        sb.AppendLine();

        sb.AppendLine("[groups]");

        var owners = state.Users
            .Where(u => u.IsActive && u.Roles.HasFlag(PortalUserRoles.Owner))
            .Select(u => u.UserName)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

        sb.Append("owners = ");
        sb.AppendLine(string.Join(", ", owners));

        if (state.Groups.Count != 0)
        {
            var activeUserNamesById = state.Users
                .Where(u => u.IsActive)
                .ToDictionary(u => u.Id, u => u.UserName);

            var directUserMembersByGroup = state.GroupMembers
                .GroupBy(m => m.GroupId)
                .ToDictionary(g => g.Key, g => g.Select(x => x.UserId).Distinct().ToArray());

            var childGroupsByGroup = state.GroupGroupMembers
                .GroupBy(m => m.GroupId)
                .ToDictionary(g => g.Key, g => g.Select(x => x.ChildGroupId).Distinct().ToArray());

            var expandedUserCache = new Dictionary<Guid, string[]>(capacity: state.Groups.Count);

            string[] ExpandUsers(Guid groupId, HashSet<Guid> stack)
            {
                if (expandedUserCache.TryGetValue(groupId, out var cached))
                {
                    return cached;
                }

                if (!stack.Add(groupId))
                {
                    // Cycle detected; ignore to keep generation stable.
                    return Array.Empty<string>();
                }

                var users = new List<string>();

                if (directUserMembersByGroup.TryGetValue(groupId, out var userIds))
                {
                    foreach (var uid in userIds)
                    {
                        if (activeUserNamesById.TryGetValue(uid, out var name) && !string.IsNullOrWhiteSpace(name))
                        {
                            users.Add(name);
                        }
                    }
                }

                if (childGroupsByGroup.TryGetValue(groupId, out var childIds))
                {
                    foreach (var child in childIds)
                    {
                        users.AddRange(ExpandUsers(child, stack));
                    }
                }

                stack.Remove(groupId);

                var result = users
                    .Where(n => !string.IsNullOrWhiteSpace(n))
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                    .ToArray();

                expandedUserCache[groupId] = result;
                return result;
            }

            foreach (var group in state.Groups.OrderBy(g => g.Name, StringComparer.Ordinal))
            {
                var members = ExpandUsers(group.Id, new HashSet<Guid>());

                sb.Append(group.Name);
                sb.Append(" = ");
                sb.AppendLine(string.Join(", ", members));
            }
        }

        foreach (var group in compiled.Groups)
        {
            sb.Append(group.Name);
            sb.Append(" = ");
            sb.AppendLine(string.Join(", ", group.Members));
        }

        sb.AppendLine();

        foreach (var section in compiled.Sections)
        {
            sb.Append('[');
            sb.Append(section.RepositoryName);
            sb.Append(':');
            sb.Append(section.Path);
            sb.AppendLine("]");
            sb.AppendLine("@owners = rw");

            if (!string.IsNullOrWhiteSpace(section.ReadGroupName))
            {
                sb.Append('@');
                sb.Append(section.ReadGroupName);
                sb.AppendLine(" = r");
            }

            if (!string.IsNullOrWhiteSpace(section.WriteGroupName))
            {
                sb.Append('@');
                sb.Append(section.WriteGroupName);
                sb.AppendLine(" = rw");
            }

            sb.AppendLine();
        }

        AtomicFileWriter.WriteAllText(AuthzPath, sb.ToString());
        return Task.CompletedTask;
    }

    private static CompiledAuthz CompileAuthz(PortalState state)
    {
        var groups = new List<GeneratedGroup>();
        var groupNamesByMembers = new Dictionary<string, string>(StringComparer.Ordinal);
        var memberKeysByGroupName = new Dictionary<string, string>(StringComparer.Ordinal);
        var sections = new List<AuthzSection>();
        var activeUsers = state.Users
            .Where(u => u.IsActive && !u.Roles.HasFlag(PortalUserRoles.Owner))
            .OrderBy(u => u.UserName, StringComparer.Ordinal)
            .ToArray();

        var rulesByRepository = state.PermissionRules
            .Where(r => r.Access is AccessLevel.None or AccessLevel.Read or AccessLevel.Write)
            .GroupBy(r => r.RepositoryId)
            .ToDictionary(g => g.Key, g => g.ToArray());

        foreach (var repo in state.Repositories.Where(r => r.IsAvailable).OrderBy(r => r.Name, StringComparer.Ordinal))
        {
            var repoRules = rulesByRepository.GetValueOrDefault(repo.Id) ?? [];
            var paths = repoRules
                .Select(r => NormalizeAuthzPath(r.Path))
                .Append("/")
                .Distinct(StringComparer.Ordinal)
                .OrderBy(p => p == "/" ? 0 : 1)
                .ThenBy(p => p, StringComparer.Ordinal)
                .ToArray();

            foreach (var path in paths)
            {
                var readUsers = new List<string>();
                var writeUsers = new List<string>();

                foreach (var user in activeUsers)
                {
                    var access = RepositoryAccessEvaluator.GetAccess(state, user.Id, repo.Id, path);
                    if (access == AccessLevel.Write)
                    {
                        writeUsers.Add(user.UserName);
                    }
                    else if (access == AccessLevel.Read)
                    {
                        readUsers.Add(user.UserName);
                    }
                }

                string? readGroupName = null;
                if (readUsers.Count > 0)
                {
                    readGroupName = GetOrAddGeneratedGroupName(
                        readUsers,
                        groups,
                        groupNamesByMembers,
                        memberKeysByGroupName);
                }

                string? writeGroupName = null;
                if (writeUsers.Count > 0)
                {
                    writeGroupName = GetOrAddGeneratedGroupName(
                        writeUsers,
                        groups,
                        groupNamesByMembers,
                        memberKeysByGroupName);
                }

                sections.Add(new AuthzSection(repo.Name, path, readGroupName, writeGroupName));
            }
        }

        return new CompiledAuthz(groups, sections);
    }

    private static string GetOrAddGeneratedGroupName(
        IReadOnlyList<string> members,
        List<GeneratedGroup> groups,
        Dictionary<string, string> groupNamesByMembers,
        Dictionary<string, string> memberKeysByGroupName)
    {
        var normalizedMembers = members
            .Where(m => !string.IsNullOrWhiteSpace(m))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(m => m, StringComparer.Ordinal)
            .ToArray();

        var memberKey = string.Join('\n', normalizedMembers);
        if (groupNamesByMembers.TryGetValue(memberKey, out var existingName))
        {
            return existingName;
        }

        var baseName = MakeGeneratedGroupName(memberKey);
        var name = baseName;
        var suffix = 2;
        while (memberKeysByGroupName.TryGetValue(name, out var existingKey)
               && !string.Equals(existingKey, memberKey, StringComparison.Ordinal))
        {
            name = $"{baseName}_{suffix}";
            suffix++;
        }

        groupNamesByMembers[memberKey] = name;
        memberKeysByGroupName[name] = memberKey;
        groups.Add(new GeneratedGroup(name, normalizedMembers));
        return name;
    }

    private static string MakeGeneratedGroupName(string memberKey)
    {
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(memberKey)))[..16].ToLowerInvariant();
        return $"svnhub_users_{hash}";
    }

    private static string NormalizeAuthzPath(string? path)
    {
        if (string.IsNullOrWhiteSpace(path) || path == "/")
        {
            return "/";
        }

        var p = path.Trim();
        if (!p.StartsWith('/'))
        {
            p = "/" + p;
        }

        while (p.Contains("//", StringComparison.Ordinal))
        {
            p = p.Replace("//", "/", StringComparison.Ordinal);
        }

        if (p.Length > 1 && p.EndsWith('/'))
        {
            p = p.TrimEnd('/');
        }

        return p;
    }

    public async Task ReloadApacheAsync(CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(_options.ApacheReloadProgram))
        {
            return;
        }

        // Windows dev mode: there is usually no Apache2/systemctl. Allow user/group/repo management
        // without failing just because the reload command isn't available.
        if (OperatingSystem.IsWindows() &&
            string.Equals(_options.ApacheReloadProgram, "systemctl", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        var args = SplitArgs(_options.ApacheReloadArguments);
        CommandResult result;
        try
        {
            result = await _runner.RunAsync(_options.ApacheReloadProgram, args, cancellationToken);
        }
        catch (InvalidOperationException ex) when (OperatingSystem.IsWindows() &&
                                                   ex.InnerException is Win32Exception { NativeErrorCode: 2 })
        {
            return;
        }

        if (!result.IsSuccess)
        {
            throw new InvalidOperationException(
                $"Apache reload failed (exit {result.ExitCode}): {result.StandardError}".Trim());
        }
    }

    private static IReadOnlyList<string> SplitArgs(string args)
    {
        if (string.IsNullOrWhiteSpace(args))
        {
            return [];
        }

        // MVP: basic split by whitespace; if you need complex quoting, switch to a real shell-arg parser.
        return args.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
    }

    private sealed record CompiledAuthz(
        IReadOnlyList<GeneratedGroup> Groups,
        IReadOnlyList<AuthzSection> Sections);

    private sealed record GeneratedGroup(string Name, IReadOnlyList<string> Members);

    private sealed record AuthzSection(
        string RepositoryName,
        string Path,
        string? ReadGroupName,
        string? WriteGroupName);
}
